# # Application name
# # spring.application.name=Project3Backend

# # Database Connection URL
# # Replace 'localhost:3306' with your host if it's different
# # Replace 'your_database_name' with the name you want to create
# spring.datasource.url=jdbc:mysql://localhost:3306/project3db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC

# # Database Credentials
# spring.datasource.username=root
# spring.datasource.password=@Inganathi0734999777

# # JDBC Driver
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
